[package]
name = "casetest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519 = "2.2.3"
ed25519-dalek = "2.1.1"
rand = "0.8.5"
ring = "0.16.20"
sha2 = "0.10.8"
